Repository ni/nisystemlink-clients-python, pull requests merged in 2020-08, with the labels that each got.

#9 Fix running SystemLink Server integration tests
  conftest.py
Labels: tests

#10 Bump version after release
  docs/conf.py
  setup.py
Labels: release

#11 Ensure nisystemlink-clients-python treats systemlink as an implicit namespace package
  .github/workflows/python-package.yml
  .gitignore
  mypy.ini
  pyproject.toml
  setup.py
  tox.ini
Labels: bug

#12 Bump version after release
  docs/conf.py
  setup.py
Labels: release
